FROM node:14 AS build
RUN mkdir /src
WORKDIR /src
ENV PATH /src/node_modules/.bin:$PATH
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build:script && git init
CMD ["nodemon", "server/index.js"]

FROM node:14-alpine AS production
WORKDIR /src
ENV PATH /src/node_modules/.bin:$PATH
COPY --from=build /src ./
RUN rm -rf node_modules \
    && rm -rf .git \
    && npm install --only=production
CMD ["node", "server/index.js"]
