FROM node:9.11.1

# set working directory
RUN mkdir /src
WORKDIR /src

# install app dependencies
ENV PATH /src/node_modules/.bin:$PATH
COPY . .

RUN npm install
RUN npm run build:script

# start app
CMD ["npm", "start"]
