FROM postgres:11.3 as staging

VOLUME jg_data_staging

# run sessions.sql on init
COPY ./sessions.sql /docker-entrypoint-initdb.d

FROM postgres:11.3 as production

VOLUME jg_data

# run sessions.sql on init
COPY ./sessions.sql /docker-entrypoint-initdb.d
