FROM postgres:11.3 as staging

VOLUME jg_data_staging

# restore database on init
COPY init.sh ./jg_db_dump_staging*.sql /docker-entrypoint-initdb.d/

FROM postgres:11.3 as production

VOLUME jg_data

# optional restore database on init
COPY init.sh ./jg_db_dump_prod*.sql /docker-entrypoint-initdb.d/
